#!/usr/bin/env bash

IMAGE_TAG="${1}"

if [ "${IMAGE_TAG}" == "" ]; then
	echo "Usage: ./build_image IMAGE_TAG"
	exit 1
fi

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
PROJECT_DIR="$( readlink -f "${SCRIPT_DIR}/.." )"
DOCKER_DIR="${PROJECT_DIR}/docker"

docker build \
	--file "${DOCKER_DIR}/Dockerfile" "${PROJECT_DIR}" \
	--tag "${IMAGE_TAG}"
